#include <stdio.h>

// This file reads data from the binary file generated by the simulation.
static FILE *bin_file;

int init_parser(char *fp) {
	bin_file = fopen(fp, "rb");
	if (bin_file == NULL) {
		printf("Error: cannot open binary file %s\n", fp);
		return -1;
	}
	return 0;
}